apiVersion: v1
kind: Secret
metadata: 
  namespace: three-tier
  name: postgres-sec
type: Opaque
data:  
  password: sdfvsnfsfsss243 # Replace with actual base64-encoded password
  username: admin # Replace with actual base64-encoded username
