apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: three-tier
spec: 
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30080
    protocol: TCP
  type: NodePort
  selector:
    role: api